<project>

    <modelVersion>4.0.0</modelVersion>

    <groupId>kbtu.lab6</groupId>
    <artifactId>lab6</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>post-service</module>
        <module>feed-service</module>
        <module>common-events</module>
    </modules>

</project>